#pragma config(Hubs,  S4, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S4_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C4_1,    release,              tServoStandard)
#pragma config(Servo,  srvo_S4_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S4_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Buttonmap.h"


int deadband = 10;
task Drive;
task Arm;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{


	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
task main()
{
	initializeRobot();

	StartTask(Drive);

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		getJoystickSettings(joystick);

		servo[sTilt] = 255;

		if (joy1Btn(BTN_RB))
			servo[servo1] = 0;
		else
			servo[release] = 255;

		if (joy1Btn(BTN_X))
			motor[belt] = -100;
		else
			motor[belt] = 0;

		if(joy1Btn(BTN_LT))
		{
			if(servo[stilt] == 255)
			{
				servo[stilt] = 210;
				wait10Msec(30);
			}
			else
			{
				servo[stilt] = 255 ;
				wait10Msec(30);
			}
		}
	}
}

task Drive()
{
	//Define storage variables
	int rawX, rawY;
	float shapedX, shapedY;
	float leftPower, rightPower;

	while (true)
	{
		//Get joystick data
		getJoystickSettings(joystick);

		//Check if the joystick is being used on any axis
		if (abs(joystick.joy1_x1) > deadband)
			rawX = joystick.joy1_x1 - (sgn(joystick.joy1_x1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawX = 0;
		if (abs(joystick.joy1_y1) > deadband)
			rawY = joystick.joy1_y1 - (sgn(joystick.joy1_y1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawY = 0;

		//Shape the powers based on equation: y = .00888888888888(x*abs(x))+.31111111111111x
		shapedX = 0.0088888888888888888888889 * (rawX * abs(rawX)) + 0.3111111111111111111111 * rawX;
		shapedY = 0.0088888888888888888888889 * (rawY * abs(rawY)) + 0.3111111111111111111111 * rawY;

		//Determine power of each side by slowing one side and increasing the other appropriately
		leftPower = shapedY - shapedX/2;
		rightPower = shapedY + shapedX/2;

		//Finally, set the power to the motors
		motor[leftDrive] = leftPower;
		motor[rightDrive] = rightPower;
	}
}
task Arm()
{
	nMotorEncoder[lift] = 0;

	while(true)
	{
		if(joy1Btn(BTN_Y))
		{
			if (nMotorEncoder[lift] == 0)
			{
				nMotorEncoderTarget[lift] = 1000;
				motor[lift] = 100;
			}
			else
			{
				nMotorEncoderTarget[lift] = 0;
				motor[lift] = 100;
			}
		}

		 if(joy1Btn(BTN_B))
		{
			if (nMotorEncoder[lift] == 0)
			{
				nMotorEncoderTarget[lift] = 2/3 * 1000;
				motor[lift] = 100;
			}
			else
			{
				nMotorEncoderTarget[lift] = 0;
				motor[lift] = 100;
			}
		}

		if(joy1Btn(BTN_A))
		{
			if (nMotorEncoder[lift] == 0)
			{
				nMotorEncoderTarget[lift] = 1/3 * 1000;
				motor[lift] = 100;
			}
			else
			{
				nMotorEncoderTarget[lift] = 0;
				motor[lift] = 100;
			}
		}

		if (abs(joystick.joy1_y2) > deadband)
		{
			motor[lift] = sgn(joystick.joy1_y2) * (abs(joystick.joy1_y2) - deadband);
		}
		else
		{
			motor[lift] = 0;
		}
	}
}
