#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    output,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    hook,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

//Move Function
void Move(float Distance, float Speed)
{
	float countsPerInch = 20;

	float userSpeed = 0.0, distTrav = 0.0, time = 0.0, powerShiftConst = 0.3, speedPercent = 0.0;
	float leftPower = 0.0, rightPower = 0.0, leftSpeed = 0.0, rightSpeed = 0.0;
	long leftEncodCount = 0.0, rightEncodCount = 0.0, prevLeftEncodCount = 0.0, prevRightEncodCount = 0.0;

	int direction = sgn(Distance);
	Distance = abs(Distance);
	Distance *= countsPerInch;
	Speed *= countsPerInch;
	userSpeed = Speed;

	leftPower = 5;
	rightPower = 5;
	nMotorEncoder[rightRear] = 0;
	nMotorEncoder[leftRear] = 0;
	ClearTimer(T1);
	motor[leftFront] = leftPower;
	motor[leftRear] = leftPower;
	motor[rightFront] = rightPower;
	motor[rightRear] = rightPower;
	float timeElapsed = 0.0;
	float iterations = 0;
	Speed = 0;
	while (distTrav < Distance)
	{
		time = time1[T1] / 1000;
		leftEncodCount = nMotorEncoder[leftRear];
		rightEncodCount = nMotorEncoder[rightRear];
		/*if (iterations < 1.0)
		{
			timeElapsed += time;
			if (timeElapsed > iterations)
			{
				Speed += 0.25;
				iterations += 0.2;
			}
		}
		else
			Speed = userSpeed;*/
		speedPercent = -1 * log(distTrav/Distance);
		if (speedPercent > 1)
			speedPercent = 1;
		Speed *= speedPercent;
		distTrav = (leftEncodCount + rightEncodCount) / 2;
		leftSpeed = (leftEncodCount - prevLeftEncodCount) / time;
		rightSpeed = (rightEncodCount - prevRightEncodCount) / time;

		if (leftSpeed == 0)
			leftSpeed = Speed;
		if (rightSpeed == 0)
			rightSpeed = Speed;

		leftPower += (Speed - leftSpeed) * powerShiftConst;
		rightPower += (Speed - rightSpeed) * powerShiftConst;

		if (abs(leftPower) > 100)
			leftPower = 100 * sgn(leftPower);
		if (abs(rightPower) > 100)
			rightPower = 100 * sgn(rightPower);
		motor[leftFront] = direction * leftPower;
		motor[leftRear] = direction * leftPower;
		motor[rightFront] = direction * rightPower;
		motor[rightRear] = direction * rightPower;

		prevLeftEncodCount = nMotorEncoder[leftRear];
		prevRightEncodCount = nMotorEncoder[rightRear];
		ClearTimer(T1);
		writeDebugStreamLine("left: %d", leftEncodCount);
		writeDebugStreamLine("right: %d", rightEncodCount);
		writeDebugStreamLine("distance: %d", Distance);
		writeDebugStreamLine("distTrav: %d", distTrav);
	}
	motor[leftFront] = 0;
	motor[leftRear] = 0;
	motor[rightFront] = 0;
	motor[rightRear] = 0;
}
task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.

	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	////                                                   ////
	////    Add your robot specific autonomous code here.  ////
	////                                                   ////
	///////////////////////////////////////////////////////////
	///////////////////////////////////////////////////////////
	clearDebugStream();

		Move(24, 2);
}
