#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     htspb,          sensorI2CCustomFastSkipStates)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    inputstop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    IRservo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    ulraservo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    output,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

float GyroBias = 0;
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "i2c.h"


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

float avgdata = 0;
void initializeRobot()
{
	servo[hook1] = 255;
	servo[hook2] = 0;
	servo[output] = 130;
	servo[inputstop] = 235;

	for (int i = 0; i < 20; i++)
	{
		avgdata += SensorValue[Gyro];
		wait1Msec(25);
	}
	GyroBias = ((float)avgdata / 20);

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#define DEVICE (0x53) // Device address as specified in data sheet
byte _buff[6];
char POWER_CTL = 0x2D; //Power Control Register
char DATA_FORMAT = 0x31;
char DATAX0 = 0x32; //X-Axis Data 0
char DATAX1 = 0x33; //X-Axis Data 1
char DATAY0 = 0x34; //Y-Axis Data 0
char DATAY1 = 0x35; //Y-Axis Data 1
char DATAZ0 = 0x36; //Z-Axis Data 0
char DATAZ1 = 0x37; //Z-Axis Data 1

void writeTo(byte address, byte val) {
	i2c_beginTransmission(DEVICE);
	i2c_write(address);
	i2c_write(val);
	i2c_endTransmission();
}
// Reads num bytes starting from address register on device in to _buff array
void readFrom(byte address, int num) {
	i2c_beginTransmission(DEVICE);
	i2c_write(address);
	i2c_endTransmission();
	i2c_requestFrom(DEVICE, num);
	int i = 0;
	while(i2c_available())
	{
		_buff[i] = i2c_read();
		i++;
	}
	i2c_endTransmission();
}
void readAccel() {
	int howManyBytesToRead = 6;
	readFrom( DATAX0, howManyBytesToRead); //read the acceleration data from the ADXL345
	// each axis reading comes in 10 bit resolution, ie 2 bytes. Least Significat Byte first!!
	// thus we are converting both bytes in to one int
	int x = ((((int)_buff[1]) << 8) | _buff[0]) * 0.0078;
	int y = ((((int)_buff[3]) << 8) | _buff[2]) * 0.0078;
	int z = ((((int)_buff[5]) << 8) | _buff[4]) * 0.0078;
	writeDebugStreamLine("x: %f", x);
	writeDebugStreamLine("y: %f", y);
	writeDebugStreamLine("z: %f", z);
}

void setup()
{
	i2c_begin(htspb, 0, 1);
	//Put the ADXL345 into +/- 4G range by writing the value 0x01 to the DATA_FORMAT register.
	writeTo(DATA_FORMAT, 0x01);
	//Put the ADXL345 into Measurement Mode by writing 0x08 to the POWER_CTL register.
	writeTo(POWER_CTL, 0x08);
}
void loop1()
{
	readAccel(); // read the x/y/z tilt
	wait10Msec(50); // only read every 0.5 seconds
}

task main()
{
	initializeRobot();

	//waitForStart(); // Wait for the beginning of autonomous phase.
	clearDebugStream();
	setup();
	while (true)
	{
		//loop1();

	}
}
