#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     sonar,          sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     B_R,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     B_L,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     block_arm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Flag_Arm,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Winch,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    Hook,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    Claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
float GyroBias = 0; //Used to calibrate the current gyro position
int avgdata = 0; //Used to measure the current gyro position
int moveRunning = 0; //Defines whether or not the Move() function is running
#include "JoystickDriver.c" //Include file to "handle" the Bluetooth messages.
#include "move_2_wheel.c" //Includes Move() function in program
#include "turn_gyro_2_wheel.c" //Includes Turn() function in program
task watchdog(); //Defines watchdog failsafe task

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


void initializeRobot()
{
servo[Claw] = 110; //Sets Claw to closed position
servo[Hook] = 127; //Sets Hook to starting position

	bFloatDuringInactiveMotorPWM = false;

	motor(B_L) = 0; //Sets left drive motors to 0
	motor(B_R) = 0; //Sets right drive motors to 0

	 for (int i = 0; i < 20; i++)
	   {
    avgdata += SensorValue[Gyro]; //Takes 20 measurements of the gyro
    wait1Msec(25); //Pauses for 250 miliseconds
    }
	}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot(); //Executes all code in the initializeRobot() function
	StartTask( watchdog ); //Start watchdog task which is a failsafe for the Move function

	waitForStart(); //Wait for the beginning of autonomous phase
		wait10Msec(25); //Pause for 250 miliseconds

		Move(1,40); //Move away from the wall 1 inch at 40% power
		wait10Msec(25); //Pause for 250 miliseconds

		motor[block_arm] = 100; //Give 100% power to the arm motor
		wait10Msec(66); //Allow the arm to run for 660 miliseconds
		motor[block_arm] = 0; //Kill the power to the arm motor
    wait10Msec(25); //Pause for 250 miliseconds

    servo[Claw] = 10; //Move block release servo to open position (10 degrees) allowing it to drop the block
    wait10Msec(100); //Pause for 1000 miliseconds to allow the block to fall

    motor[block_arm] = -100; //Give 100% power to the arm again but in the oppisite direction
		wait10Msec(35); //Allow the arm to move back to a closed position
		motor[block_arm] = 0; //Kill the power to the arm motor
    wait10Msec(25); //Pause for 250 miliseconds

    Turn(-80); //Turn 80 degrees away from the bucket
    wait10Msec(25); //Pause for 250 miliseconds

    Move(22,75); //Move 22 inches towards the ramp at 75% power
    wait10Msec(25); //Pause for 250 miliseconds

    Turn(-55); //Turn 55 degrees towards the ramp
    wait10Msec(25); //Pause for 250 miliseconds

    Move(-55,75); //Move onto the ramp for the end of the autonomous phase
    wait10Msec(25); //Pause for 250 miliseconds
}

task watchdog() //This task is a failsafe for the Move function
{
while (true) //Allows the code to loop
{
if (moveRunning == 1) //Check if the Move() function is running...
{
if (abs(nMotorEncoder[B_L]) == 0 || abs(nMotorEncoder[B_R]) == 0) //Check if one of the encoders stops counting...
	{
		wait10Msec(100); //Wait one second
		if (abs(nMotorEncoder[B_L]) == 0 || abs(nMotorEncoder[B_R]) == 0) //Check if the encoder still isn't counting
		{
			motor[B_R] = 0; //Stops right motors
			motor[B_L] = 0; //Stops left motors
		}
	}
}
}
}
