#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Ramp_R,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          Ramp_L,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     L_Rear,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm_motor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     R_Rear,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     R_Front,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     L_Front,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    R_Wrist,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    L_Wrist,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

float GyroBias = 0;
int avgdata = 0;

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "move_2.c"
#include "turn_gyro.c"
#include "arm.c"
#include "Start.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
   // Take 20 readings of the gyro and average them out
  for (int i = 0; i < 20; i++) {
    avgdata += SensorValue[Gyro];
    wait1Msec(25);
  }
  // Store new bias
  GyroBias = ((float)avgdata / 20);

  int nDelay = 200;

  bFloatDuringInactiveMotorPWM = false;

  motor(L_Front) = 0;
  motor(L_Rear) = 0;
  motor(R_Front) = 0;
  motor(R_Rear) = 0;
  nMotorEncoder[L_Front]	= 0;
  nMotorEncoder[R_Front]	= 0;
  nMotorEncoder[Arm_motor]	= 0;

   return;
}



task main()
{
   initializeRobot();


   //Set defaults
   int distance = 12;
   int turn = 0;
   int distance2 = 12;

   //Allow display control
   StopTask(displayDiagnostics);

   //Choose first distance to move
   ClearTimer(T3);
   while (nNxtButtonPressed != 3 && time1[T3] < 3000)
   {
     if (nNxtButtonPressed == 1)
   	{
  	   distance += 6;
  	   ClearTimer(T3);
  	 }
  	 else if (nNxtButtonPressed == 2)
   	{
  	   distance -= 6;
  	   ClearTimer(T3);
  	 }
  	 nxtDisplayBigTextLine(1, "%d, %s", distance, "in.");
  	 wait10Msec(30);
  }

  wait10Msec(30);

   //Choose degrees to turn
   while (nNxtButtonPressed != 3 && time1[T3] < 3000)
   {
     if (nNxtButtonPressed == 1)
   	{
  	   turn += 15;
  	   ClearTimer(T3);
  	 }
  	 else if (nNxtButtonPressed == 2)
   	{
  	   turn -= 15;
  	   ClearTimer(T3);
  	 }
  	 nxtDisplayBigTextLine(1, "%d, %s", turn, "CCW");
  	 wait10Msec(30);
  }

  wait10Msec(30);

  //Choose second distance to move
   while (nNxtButtonPressed != 3 && time1[T3] < 3000)
   {
     if (nNxtButtonPressed == 1)
   	{
  	   distance2 += 6;
  	   ClearTimer(T3);
  	 }
  	 else if (nNxtButtonPressed == 2)
   	{
  	   distance2 -= 6;
  	   ClearTimer(T3);
  	 }
  	 nxtDisplayBigTextLine(1, "%d, %s", distance2, "in.");
  	 wait10Msec(30);
  }

  StartTask(displayDiagnostics);

  Start();

 	 Move(distance, 100.0);    // drive forward distance inches
 	 wait10Msec(10);
 	 Turn_gyro(turn);    // turn counterclockwise turn degrees
   wait10Msec(10);
   Move(distance2, 100.0);    // drive forward distance2 inches

}
