#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Ramp_R,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          Ramp_L,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     L_Rear,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm_motor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     R_Rear,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     R_Front,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     L_Front,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    R_Wrist,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    L_Wrist,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

float GyroBias = 0;
int avgdata = 0;

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "move_2.c"
#include "turn_gyro.c"
#include "wrist.c"
#include "Start.c"

//=============================================================================
// Function: initializeRobot()
//
// Description:
//    This function will initialize variables to the initial values.
//
// Parameters: degrees = degrees to rotate wrist
//=============================================================================
void initializeRobot()
{
   // Take 20 readings of the gyro and average them out
  for (int i = 0; i < 20; i++) {
    avgdata += SensorValue[Gyro];
    wait1Msec(25);
  }
  // Store new bias
  GyroBias = ((float)avgdata / 20);

  int nDelay = 200;

  bFloatDuringInactiveMotorPWM = false;

  motor(L_Front) = 0;
  motor(L_Rear) = 0;
  motor(R_Front) = 0;
  motor(R_Rear) = 0;
  nMotorEncoder[L_Front]	= 0;
  nMotorEncoder[R_Front]	= 0;
  nMotorEncoder[Arm_motor]	= 0;

   return;
}

//=============================================================================
// Function: main()
//
// Description:
//    This is an autonomous program that will just move the bot and score
//    on one of the lower pegs.
//
// Parameters: degrees = degrees to rotate wrist
//=============================================================================
task main()
{
   initializeRobot();

   Start();

 	Move(10, 70.0);
 	wait10Msec(10);
   
 	Turn_gyro(-90);
   wait10Msec(10);
   
 	Move(55, 70.0);
 	wait10Msec(10);
   
 	Turn_gyro(65);
   wait10Msec(10);
   
   Wrist(180.0, 70.0);
 	wait10Msec(10);
   
 	Move(30, 70.0);
 	wait10Msec(10);
   
   Arm(20.0, 70.0);
 	wait10Msec(10);
   
} // End main() task
