#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          Ramp_R,        tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          Ramp_L,        tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     L_Rear,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     Arm_motor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     R_Rear,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     R_Front,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     L_Front,       tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C4_1,    R_Wrist,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    L_Wrist,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// ***********	Globals *********

int deadband = 10;
//float armEncoder = nMotorEncoder[Arm_motor];

// *********** Include files ********

#include "JoystickDriver.c"	 //Include file to "handle" the Bluetooth messages.


// *********** Prototypes ********
task drive();
task Arm();



void initializeRobot()
{
	// Place code here to initialize servos to starting positions.
	return;
}


task main()
{

	//	waitForStart();	 // wait for start of tele-op phase

	StartTask( drive );
	StartTask( Arm );
		//Allow display control
StopTask(displayDiagnostics);
eraseDisplay();


	float watchedmessage;
	//int watch = 1;
	while(true)
	{
		watchedmessage = ntotalMessageCount; // grabs the number of Messages and names it watchedMessage

		wait10Msec(25); // give the Messagecount time to change it changes every 50ms

		if(watchedmessage == ntotalMessageCount) // checks to see if the Message change if has not it is Disconnected
		{                // if Disconnected it runs this
			motor[mtr_S1_C1_1] = 0; // stops motor
			motor[mtr_S1_C1_2] = 0;
			motor[mtr_S1_C2_1] = 0;
			motor[mtr_S1_C2_2] = 0;
			motor[mtr_S1_C3_1] = 0;
			motor[mtr_S1_C3_2] = 0;

			//StopTask(main); //stops task robot control task
			StopTask(drive);
			StopTask(Arm);

			wait1Msec(10); //gives time to spot

			//StartTask(main); //restart task incase of reconnection
			StartTask(drive);
			StartTask(Arm);

			nxtDisplayTextLine(2, "DISCONNECTED"); //displays DISCONNECTED to tell you if you are Disconnected
		}
		else//if the Message change you are connected
		{

			nxtDisplayTextLine(2, "CONNECTED"); //displays CONNECTED to tell you if everything is working

		}
	}

}

task Arm()
{
	int armPosition;
	// Since the PID is set for speed control, the motor value
	// is speed, not power.
	int armSpeed = 0;
	float delta = 0;
	float diff = 0;
	const float MHP = 50.0; //Max Hold Power
	const float DEAD_BAND = 5.0; // Deadband for hold tolerance
	int holdPower = 0;


	float encoderCount;
	nMotorEncoder[Arm_motor] = 0;
	nMotorPIDSpeedCtrl[Arm_motor] = mtrSpeedReg;
	nMaxRegulatedSpeed12V = 1000;
	//int servoPosition = 0;
	//bool servoForward = true;
	//	bool clawOpen = true;
	while (true)
	{
		nxtDisplayBigTextLine(2, "%d, %s", nMotorEncoder[Arm_motor], "counts");
		//----------------------------------------------
		// If the Joystick is beyond the deadband area,
		// move the arm based on the position of the
		// joystick.
		//----------------------------------------------
		while(abs(joystick.joy1_y2) > deadband)
		{
			// Set the speed based on the joystick position
			armSpeed = ((float)joystick.joy1_y2 / 127.0) * 15;
			motor[Arm_motor] = armSpeed;

		} // End if the arm is beyond the deadband

		// Stop the motor and reset the encoder to zero
		// for a good reference point. (keep it from wrapping
		motor(Arm_motor) = 0;
//		nMotorEncoder[Arm_motor] = 0;
		armPosition = 0;

		//----------------------------------------------
		// If the arm moves 5 encoder points from its
		// position, then move it back.
		//----------------------------------------------
		if(armPosition != nMotorEncoder[Arm_motor])
		{
			delta = armPosition - nMotorEncoder[Arm_motor];
			diff = abs( delta ) - DEAD_BAND;
			if( diff > 0 )
			{
				//holdPower = ( DEAD_BAND / delta ) * MHP;
				holdPower = ( diff / DEAD_BAND ) * MHP * sgn( delta );
				motor[Arm] = holdPower;
			}
		}

		getJoystickSettings(joystick);
		if(abs(joystick.joy1_y2) > deadband)
		{
			motor[Arm] = joystick.joy1_y2;///3;
		}

	}

}


task drive()
{
	int rampup = 50;
	int startmove = 0;
	int deadband = 10;

	while (true)
	{
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y1) > deadband || abs(joystick.joy1_x1) > deadband)
		{
			if(abs(joystick.joy1_y1) > abs(joystick.joy1_x1))
			{
				if(joystick.joy1_y1 < 0)
				{
					rampup = rampup * -1;
				}

				if(startmove == 0)
				{
					motor[L_Front] =	rampup;
					motor[R_Front] =	rampup;
					motor[L_Rear] = rampup;
					motor[R_Rear] = rampup;
					startmove = 1;
				}
				else
				{

					motor[L_Front] =	-joystick.joy1_y1;
					motor[R_Front] =	-joystick.joy1_y1;
					motor[L_Rear] = -joystick.joy1_y1;
					motor[R_Rear] = -joystick.joy1_y1;

				}

			}
			else if(abs(joystick.joy1_y1) <	 abs(joystick.joy1_x1))
			{
				motor[L_Front] =	-joystick.joy1_x1;
				motor[R_Front] =	joystick.joy1_x1;
				motor[L_Rear] = -joystick.joy1_x1;
				motor[R_Rear] = joystick.joy1_x1;
			}
			else if(abs(joystick.joy1_y1) < deadband || abs(joystick.joy1_x1) < deadband)
			{
				motor[L_Front] =	0;
				motor[R_Front] =	0;
				motor[L_Rear] = 0;
				motor[R_Rear] = 0;
				startmove = 0;
				rampup = 50;

			}
		}

		else
		{
			motor[L_Front] =	0;
			motor[R_Front] =	0;
			motor[L_Rear] = 0;
			motor[R_Rear] = 0;
			startmove = 0;
			rampup = 50;
		}

		if(joy1Btn( 8 ))			// If button 8 (bottom right trigger) is pressed, turn wrist one way
		{
			if (ServoValue[L_Wrist] > 0 && ServoValue[R_Wrist] < 255)
			{
				servo[L_Wrist] = ServoValue[L_Wrist]-6;
				servo[R_Wrist] = ServoValue[R_Wrist]+6;
			}
		}
		if(joy1Btn( 6 ))			// If button 6 (top right trigger) is pressed, turn wrist the other way
		{
			if (ServoValue[L_Wrist] < 255 && ServoValue[R_Wrist] > 0 )
			{
				servo[L_Wrist] = ServoValue[L_Wrist]+6;
				servo[R_Wrist] = ServoValue[R_Wrist]-6;
			}
		}

	}
}
