#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Accel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    srelease,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    stilt,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    sdunk,                tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Buttonmap.h"


int deadband = 10;
task Drive;
task Arm;
task watchdog;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


task main()
{
	initializeRobot();

	StartTask(Drive);
	StartTask(Arm);
	StartTask(watchdog);


	waitForStart();   // wait for start of tele-op phase
	servo[stilt] = 35;
	servo[sdunk] = 245;
	servo[srelease] = 245;
	while (true)
	{
		getJoystickSettings(joystick);


		if (joy1Btn(BTN_RB))
			if (servo[srelease] < 100)
			{
				servo[srelease] = 245;
				wait10Msec(50);
			}
			else if (servo[srelease] > 100 /*|| joy1Btn(BTN_X)*/)
			{
				servo[srelease] = 0;
				wait10Msec(50);
			}

			if (joy1Btn(BTN_RT))
			if (servo[sdunk] < 100)
			{
				servo[sdunk] = 245;
				wait10Msec(50);
			}
			else if (servo[sdunk] > 100 /*|| joy1Btn(BTN_X)*/)
			{
				servo[sdunk] = 0;
				wait10Msec(50);
			}


		if (joy1Btn(BTN_X))
		{
		//	servo[srelease] = 255;
			motor[belt] = -100;
		}

		else if (joy1Btn(BTN_LB))
		{
		//	servo[srelease] = 255;
			motor[belt] = 100;
		}
		else if (!joy1Btn(BTN_LB) && !joy1Btn(BTN_X))
			motor[belt] = 0;

		if (joy1Btn(BTN_LT))
		{
			if (servo[stilt] == 0)
			{
				servo[stilt] = 35;
				wait10Msec(50);
			}
			else if (servo[stilt] == 35)
			{
				servo[stilt] = 0;
				wait10Msec(50);
			}
		}


	}
}

task Drive()
{
	//Define storage variables
	int rawX, rawY;
	float shapedX, shapedY;
	float leftPower, rightPower;

	while (true)
	{
		//Get joystick data
		getJoystickSettings(joystick);

		//Check if the joystick is being used on any axis
		if (abs(joystick.joy1_x1) > deadband)
			rawX = joystick.joy1_x1 - (sgn(joystick.joy1_x1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawX = 0;
		if (abs(joystick.joy1_y1) > deadband)
			rawY = joystick.joy1_y1 - (sgn(joystick.joy1_y1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawY = 0;


		shapedX = 0.00889 * (rawX * abs(rawX)) + 0.13333 * rawX;
		shapedY = 0.00889 * (rawY * abs(rawY)) + 0.13333 * rawY;

		//Determine power of each side by slowing one side and increasing the other appropriately
		leftPower = shapedY + shapedX/2;
		rightPower = shapedY - shapedX/2;

		//Finally, set the power to the motors
		motor[leftDrive] = leftPower;///*leftPower*/ joystick.joy1_y1;
		motor[rightDrive] = rightPower;///*rightPower*/ joystick.joy1_y1;
	}
}
task Arm()
{
	nMotorEncoder[lift] = 0;
	int dead = 10;
	bool Moving = false;

	while(true)
	{
		if(joy1Btn(BTN_Y))
		{
				nMotorEncoderTarget[lift] = 1000;
				motor[lift] = 100;
				Moving = true;
		}

		 if(joy1Btn(BTN_B))
		{
				nMotorEncoderTarget[lift] = 2/3 * 1000;
				motor[lift] = 100;
				Moving = true;
		}

		if(joy1Btn(BTN_A))
		{
				nMotorEncoderTarget[lift] = 1/3 * 1000;
				motor[lift] = 100;
				Moving = true;
		}
		if (Moving)
		{
			if ((nMotorEncoder[lift] < nMotorEncoderTarget[lift] - dead) && (nMotorEncoder[lift] > nMotorEncoderTarget[lift] + dead))
			{
				motor[lift] = 0;
				Moving = false;
		  }

		}
//end of experimental code

		else if (abs(joystick.joy1_y2) > deadband)
		{
			motor[lift] = sgn(joystick.joy1_y2) * (abs(joystick.joy1_y2) - deadband);
		}
		else
		{
			motor[lift] = 0;
		}
	}
}

task watchdog()
{
	while(true)
	{
		int watchedmessage = ntotalMessageCount; // grabs the number of Messages and names it watchedMessage

		wait10Msec(25); // give the Messagecount time to change it changes every 50ms

		if(watchedmessage == ntotalMessageCount) // checks to see if the Message change if has not it is Disconnected
		{                // if Disconnected it runs this
			motor[mtr_S1_C1_1] = 0; // stops motor
			motor[mtr_S1_C1_2] = 0;
			motor[mtr_S1_C2_1] = 0;
			motor[mtr_S1_C2_2] = 0;
			motor[mtr_S1_C3_1] = 0;
			motor[mtr_S1_C3_2] = 0;


			StopTask(main); //stops task robot control task
			StopTask(Drive);

			wait1Msec(10); //gives time to spot

			StartTask(main); //restart task incase of reconnection
			StartTask(Drive);

			nxtDisplayTextLine(2, "DISCONNECTED"); //displays DISCONNECTED to tell you if you are Disconnected
		}
		else//if the Message change you are connected
		{

			nxtDisplayTextLine(2, "CONNECTED"); //displays CONNECTED to tell you if everything is working

		}
	}
}
