#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker600)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     Aim,           tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     B_L,           tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     block_arm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Flag_Arm,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     test,          tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     Winch,         tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    Hook,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    Claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    leftAim,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    release,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation                 of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
float GyroBias = 0; //Used to calibrate the current gyro position
int avgdata = 0; //Used to measure the current gyro position
int moveRunning = 0; //Defines whether or not the Move() function is running
float COUNTS_PER_INCH = 57.05;
int distRemain;
float distTravelled;
float pendulumLength = 48+8;//********************needs checking********************
bool IRFound = false; //Reports if IR is found
#include "JoystickDriver.c" //Include file to "handle" the Bluetooth messages.
//#include "move_2_wheel.c" //Includes Move() function in program
//#include "turn_gyro_2_wheel.c" //Includes Turn() function in program
#include "Start.c" //Includes Start() function in program that allows bypass of waitForStart()
task watchdog(); //Defines watchdog failsafe task


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	servo[Claw] = 200; //Sets Claw to closed position
	servo[Hook] = 35; //Sets Hook to starting position
	servo[release] = 0;

	bFloatDuringInactiveMotorPWM = false;
	bNxtLCDStatusDisplay = false;
	//nMotorPIDSpeedCtrl[Aim]= mtrSpeedReg;
	//nMaxRegulatedSpeed12V = 1000;

	motor(B_L) = 0; //Sets left drive motors to 0
	//motor(B_R) = 0; //Sets right drive motors to 0

	for (int i = 0; i < 20; i++)
	{
		avgdata += SensorValue[Gyro]; //Takes 20 measurements of the gyro
		wait1Msec(25); //Pauses for 250 miliseconds
	}
}

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void shoot()
{
	float v = 4.5;
	float g = 9.78;
	float theta;
	float angle;
	float range;
	float rate;
	int speed = 1;

	range = 88;//SensorValue[sonar];
	rate = 1440/(90);
	range = ((range)/100);
	theta = radiansToDegrees(asin(((range*g))/(v*v))/2);

	angle = theta*rate;
	nxtDisplayTextLine(2, "theta: %f", angle);
	nMotorEncoder[Aim] = 0;
	motor[Aim] = speed;
	while (abs(nMotorEncoder[Aim]) < angle)
	{
		nxtDisplayTextLine(2, "theta: %f", nMotorEncoder[Aim]);
	}

	motor[Aim] = 0;

	wait10Msec(100);
	servoChangeRate[release] = 50;

	servo[release] = 255;
	wait10Msec(200);
	servo[release] = 0;
}

int scanIR()
{
	if (SensorValue[IR] == 5)
	{
		return 1;
	}
	else
	{
		return 0;
	}
}


task main()
{
	initializeRobot();

	Start(); // Wait for the beginning of autonomous phase.

	int count = 0;

/*	while (scanIR() != 1)
	{
		count += 1;
		if (count == 1 || count == 3)
		{
			Move(10,50);
		}
		else if (count == 2)
		{
			Move(18,50);
		}
		else
		{
			break;
		}
		wait10Msec(200);
	}*/
	shoot();

}

task watchdog() //This task is a failsafe for the Move function
{
	while (true) //Allows the code to loop
	{
		nxtDisplayTextLine(2, "avg: %d", SensorValue[IR]);
		/*if (moveRunning == 1) //Check if the Move() function is running...
		{
		if (abs(nMotorEncoder[B_L]) == 0 || abs(nMotorEncoder[B_R]) == 0) //Check if one of the encoders stops counting...
		{
		wait10Msec(100); //Wait one second
		if (abs(nMotorEncoder[B_L]) == 0 || abs(nMotorEncoder[B_R]) == 0) //Check if the encoder still isn't counting
		{
		motor[B_R] = 0; //Stops right motors
		motor[B_L] = 0; //Stops left motors
		}
		}
		}*/
	}
}
