#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     Accel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     rightDrive,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     leftDrive,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "drivers\hitechnic-accelerometer.h"
#include "Accel_Move_Function"
int deadband = 10;


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();
 const float Conversion = 386.09/200;
	int X_axis;
  int Y_axis;
  int Z_axis;
  int time;
  int delta_time;
  int time_old;
  int accel_old;
  int accel_new;
  float velocity_old;
  float velocity_new;
  float distance_driven;

  clearDebugStream();
  ClearTimer(T3);
  time_old = nPgmTime;
  accel_old = 0.0;
  velocity_old = 0;
  velocity_new = 0;
  distance_driven = 0;

  while(true)
  {
  		HTACreadAllAxes(Accel, X_axis, Y_axis, Z_axis);

  		time =  nPgmTime; // this timer wraps around

    	delta_time = abs(time - time_old); // delta time in ms

    	if (delta_time < 1) // protect against divide by zero
    	{
      delta_time = 1;
    	 }

    	accel_new = (X_axis) * Conversion;

    	velocity_new = velocity_old + 0.001 * (float)delta_time * 0.5 *(accel_new + accel_old);

			distance_driven += 0.001 * (float)delta_time * 0.5 *(velocity_new + velocity_old);

    	time_old = time;
   		accel_old = accel_new;
   		velocity_old = velocity_new;
    	writeDebugStreamLine("X:%d, Y:%d, Z:%d\nVelocity:%f, Distance:%f\n",X_axis, Y_axis, Z_axis, velocity_new,distance);
    	wait10Msec(3);

    if(distance_driven < distance * 0.80)
    {
    	motor[leftDrive] += 10;
    	motor[rightDrive] += 10;
  	}

  	else if (distance_driven > distance * 0.80 && distance_driven < distance * 0.20)
  	{
  		motor[leftDrive] = 100;
    	motor[rightDrive] = 100;
    }

    else
    {
    	motor[leftDrive] += 10;
    	motor[rightDrive] += 10;
    }
  }}
