#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     Accel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     belt,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    srelease,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    sgrab,                tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Buttonmap.h"
int deadband = 10;
task Drive;
task Arm;


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  StartTask(Drive);
  StartTask(Arm);

	waitForStart();   // wait for start of tele-op phase

	servo[srelease] = 120;
	servo[sgrab] = 185;
	while (true)
	{
		getJoystickSettings(joystick);
///////////////////////////////////
//      Release Mechanism        //
///////////////////////////////////
		if (joy1Btn(BTN_RT))
		{
			if (servo[srelease] < 170)
			{
				servo[srelease] = 255;
				wait10Msec(50);
			}
			else if (servo[srelease] > 170)
			{
				servo[srelease] = 120;
				wait10Msec(50);
			}
		}

///////////////////////////////////
//         Goal Grabber          //
///////////////////////////////////
		if (joy1Btn(BTN_LT))
		{
			if (servo[sgrab] >= 245)
			{
				servo[sgrab] = 185; //up
				wait10Msec(50);
			}
			else if (servo[sgrab] == 185)
			{
				servo[sgrab] = 250; //down
				wait10Msec(50);
			}
		}


///////////////////////////////////
//        Conveyor Belt          //
///////////////////////////////////
		if (joy1Btn(BTN_X))
		{
			motor[belt] = -100;
		}

		else if (joy1Btn(BTN_LB))
		{
			motor[belt] = 100;
		}
		else if (!joy1Btn(BTN_LB) && !joy1Btn(BTN_X))
			motor[belt] = 0;

	}
}

task Drive()
{
	//Define storage variables
	int rawX, rawY;
	float shapedX, shapedY;
	float leftPower, rightPower;

nMotorEncoder[leftDrive] = 0;
nMotorEncoder[rightDrive] = 0;
	while (true)
	{

		//Get joystick data
		getJoystickSettings(joystick);

		//Check if the joystick is being used on any axis
		if (abs(joystick.joy1_x1) > deadband)
			rawX = joystick.joy1_x1 - (sgn(joystick.joy1_x1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawX = 0;
		if (abs(joystick.joy1_y1) > deadband)
			rawY = joystick.joy1_y1 - (sgn(joystick.joy1_y1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawY = 0;


		shapedX = 0.00889 * (rawX * abs(rawX)) + 0.13333 * rawX;
		shapedY = 0.00889 * (rawY * abs(rawY)) + 0.13333 * rawY;

		//Determine power of each side by slowing one side and increasing the other appropriately
		leftPower = shapedY - shapedX/2;
		rightPower = shapedY + shapedX/2;

		//Finally, set the power to the motors
		motor[leftDrive] = leftPower;///*leftPower*/ joystick.joy1_y1;
		motor[rightDrive] = rightPower;///*rightPower*/ joystick.joy1_y1;

				writeDebugStream( "left: %d\n", nMotorEncoder[leftDrive] );
		writeDebugStream( "right: %d", nMotorEncoder[rightDrive] );
	}
}
task Arm()
{
	nMotorEncoder[lift] = 0;

	while(true)
	{


		if (abs(joystick.joy1_y2) > deadband)
		{
			motor[lift] = sgn(joystick.joy1_y2) * (abs(joystick.joy1_y2) - deadband);
		}
		else
		{
			motor[lift] = 0;
		}
	}
}
