#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     accel,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    output,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-accelerometer.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{


	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void Move(float distance, float power)
{
	float offset = 0;
	int xRaw, yRaw, zRaw = 0;

	float xAccel = 0;
	float prevXAccel = 0;
	float prevXRaw = 0;

	int timeOld = 0;//, timeNew = 0;
	float deltaTime = 0;

	float velocity = 0;
	float prevVelocity = 0;

	float dist = 0;
	float distActual = 0;

	//float mPowers = 0;
	power = abs(power) * sgn(distance);
	distance = abs(distance);

	float accelBias = 0;
	for (int i = 0; i < 20; i++)
	{
		HTACreadAllAxes(accel, xRaw, yRaw, zRaw);

		//accelBias += sqrt(Pow(xRaw, 2) + Pow(yRaw, 2) + Pow(zRaw, 2));
		accelBias += xRaw;
	}
	offset = accelBias/20;
	writeDebugStreamLine("%f", offset);
	ClearTimer(T1);
	//timeNew = nPgmTime;
	int rampUpCount = 300*0.05;
	float setPower = 0;
	while (true)
	{
		if (abs(distActual) < distance)
		{
			//if (rampUpCount <= 300)
			//	rampUpCount += 1;
		  //setPower = -log(dist/distance) * power;
			setPower = power;
		  if (setPower > power)
		  	setPower = power;
			motor[rightFront] = setPower;// * rampUpCount/100;
			motor[rightRear] = setPower;// * rampUpCount/100;
			motor[leftFront] = setPower;// * rampUpCount/100;
			motor[leftRear] = setPower;// * rampUpCount/100;
			HTACreadAllAxes(accel, xRaw, yRaw, zRaw);

			//xAccel = sgn(xRaw) * (sqrt(Pow(xRaw, 2) + Pow(yRaw, 2) + Pow(zRaw, 2)-Pow(offset, 2)) / 200.0) * 386.09;
			//writeDebugStreamLine("%f",sqrt(abs(Pow(xRaw, 2) + Pow(yRaw, 2) + Pow(zRaw, 2) - Pow(offset, 2))));
			xAccel = (((float)xRaw - offset)/ 200.0) * 386.09;
			//writeDebugStreamLine("%f",xAccel);
			deltaTime = time1[T1] * 0.001;
			//deltaTime = (timeNew - timeOld) * 0.001;

			if (abs(xAccel) <= 0.01)
				xAccel = 0;

			velocity += deltaTime/2 * (prevXAccel + xAccel);
			dist += deltaTime/2 * (prevVelocity + velocity);

			distActual = 0.010073 * pow(dist, 2) + 0.676081 * abs(dist) + 7.603809;

			writeDebugStreamLine("Accel: %f", dist);


			ClearTimer(T1);
			//timeOld = timeNew;
			prevXAccel = xAccel;
			prevVelocity = velocity;
			wait1Msec(10);
			/*prevXRaw = xRaw;
			do
			{
				HTACreadAllAxes(accel, xRaw, yRaw, zRaw);
			}while(xRaw == prevXRaw);*/
		}
		else
		{
			motor[rightFront] = 0;
			motor[rightRear] = 0;
			motor[leftFront] = 0;
			motor[leftRear] = 0;
		}
	}
}

task main()
{
	initializeRobot();

	clearDebugStream();
	//waitForStart();   // wait for start of tele-op phase

	Move(-30, 40);
}
