#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     htspb,          sensorNone)
#pragma config(Sensor, S4,     ir,             sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    inputstop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    irTurret,             tServoStandard)
#pragma config(Servo,  srvo_S1_C1_5,    ulraservo,            tServoStandard)
#pragma config(Servo,  srvo_S1_C1_6,    output,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	clearDebugStream();
	int servoVal = 0;
	servo[irTurret] = servoVal;
	wait10Msec(100);
	while (true)
	{
		for (int i = 0; i < 5; i++)
		{
			servoVal++;
			servo[irTurret] = 70 + i;
			eraseDisplay();
  		nxtDisplayCenteredBigTextLine(1, "IR: %d", SensorValue[ir]);
  		nxtDisplayCenteredBigTextLine(4, "Ser: %d", 70 + I);

			//if (SensorValue[ir] == 6 || (SensorValue[ir] == 0 && irPrev == 7))
			//	break;
			wait10Msec(50);
		}
	}
	while (true){}
}
