#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     rightRear,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     leftFront,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     leftRear,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Servo,  srvo_S1_C1_1,    output,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_3,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "Buttonmap.h"
int deadband = 10;
float driveFraction = 1.0;
bool driving = false;
int driveStyle = 0;
task AwesomeDrive;
task LameDrive;
task Arm;
task Buttons;

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
				servo[output] = 130;
				servo[hook1] = 255;
				servo[hook2] = 0;


	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
task AwesomeDrive()
{
	//Define storage variables
	int rawX, rawY;
	float shapedX, shapedY;
	float leftPower, rightPower;
	driveStyle = 0;

	while (true)
	{
		//Get joystick data
		getJoystickSettings(joystick);

		//Check if the joystick is being used on any axis
		if (abs(joystick.joy1_x1) > deadband)
			rawX = joystick.joy1_x1 - (sgn(joystick.joy1_x1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawX = 0;
		if (abs(joystick.joy1_y1) > deadband)
			rawY = joystick.joy1_y1 - (sgn(joystick.joy1_y1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawY = 0;

		//Shape the powers based on equation: y = (2/225)(x*abs(x))+(14/45)x
		shapedX = 0.0088888888888889 * (rawX * abs(rawX)) + 0.3111111111111111 * rawX;
		shapedY = 0.0088888888888889 * (rawY * abs(rawY)) + 0.3111111111111111 * rawY;
		//shapedX = (float)(2/225) * (rawX * abs(rawX)) + (float)(14/45) * rawX;
		//shapedY = (float)(2/225) * (rawY * abs(rawY)) + (float)(14/45) * rawY;

		//Determine power of each side by slowing one side and increasing the other appropriately
		leftPower = shapedY + shapedX/2;
		rightPower = shapedY - shapedX/2;

		//Finally, set the power to the motors
		motor[leftFront] = leftPower * driveFraction;
		motor[leftRear] = leftPower * driveFraction;
		motor[rightFront] = rightPower * driveFraction;
		motor[rightRear] = rightPower * driveFraction;

		if (abs(leftPower) > 0 || abs(rightPower) > 0)
			driving = true;
		else
			driving = false;

		if (joy1Btn(BTN_SELECT))
		{
			wait10Msec(30);
			StartTask(LameDrive);
			break;
		}
	}
}

task LameDrive()
{
	//Define storage variables
	int rawLeft, rawRight;
	float shapedLeft, shapedRight;
	driveStyle = 1;

	while (true)
	{
		//Get joystick data
		getJoystickSettings(joystick);

		//Check if the joystick is being used on any axis
		if (abs(joystick.joy1_y1) > deadband)
			rawLeft = joystick.joy1_y1 - (sgn(joystick.joy1_y1) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawLeft = 0;
		if (abs(joystick.joy1_y2) > deadband)
			rawRight = joystick.joy1_y2 - (sgn(joystick.joy1_y2) * deadband); //Set variables and subtract deadband from total to avoid jump
		else
			rawRight = 0;

		//Shape the powers based on equation: y = (2/225)(x*abs(x))+(14/45)x
		shapedLeft = 0.0088888888888889 * (rawLeft * abs(rawLeft)) + 0.3111111111111111 * rawLeft;
		shapedRight = 0.0088888888888889 * (rawRight * abs(rawRight)) + 0.3111111111111111 * rawRight;

		//Finally, set the power to the motors
		motor[leftFront] = shapedLeft * driveFraction;
		motor[leftRear] = shapedLeft * driveFraction;
		motor[rightFront] = shapedRight * driveFraction;
		motor[rightRear] = shapedRight * driveFraction;

		if (abs(shapedLeft) > 0 || abs(shapedRight) > 0)
			driving = true;
		else
			driving = false;

		if (joy1Btn(BTN_SELECT))
		{
			wait10Msec(30);
			StartTask(AwesomeDrive);
			break;
		}
	}
}

task Arm()
{
	while(true)
	{
		getJoystickSettings(joystick);
		if (joy1Btn(BTN_LB) && !joy1Btn(BTN_LT))
			motor[lift] = 75;
		else if (joy1Btn(BTN_LT) && !joy1Btn(BTN_LB))
			motor[lift] = -75;
		else
			motor[lift] = 0;

		if (joy1Btn(BTN_RB) && !joy1Btn(BTN_RT))
			motor[intake] = 100;
		else if (joy1Btn(BTN_RT) && !joy1Btn(BTN_RB))
			motor[intake] = -100;
		else
			motor[intake] = 0;
	}
}

task Buttons()
{
	while (true)
	{
		getJoystickSettings(joystick);

		if (joy1Btn(BTN_A))
		{
			if (servo[output] < 190)
				servo[output] = 235;
			else
				servo[output] = 130;
			wait10Msec(40);
		}
		if (joy1Btn(BTN_X))
		{
			if (servo[hook1] > 180)
			{
				servo[hook1] = 0;
				servo[hook2] = 255;
			}
			else
			{
				servo[hook1] = 255;
				servo[hook2] = 0;
			}
			wait10Msec(40);
		}
	}
}


task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	clearDebugStream();
	StartTask(AwesomeDrive);
	StartTask(Arm);
	StartTask(Buttons);

	long messageCountPrev = 0;
	while (true)
	{
		if (messageCountPrev == ntotalMessageCount)
		{
			StopTask(AwesomeDrive);
			StopTask(Arm);
			StopTask(Buttons);
			StopTask(LameDrive);

			motor[mtr_S1_C2_1] = 0;
			motor[mtr_S1_C2_2] = 0;
			motor[mtr_S1_C3_1] = 0;
			motor[mtr_S1_C3_2] = 0;
			motor[mtr_S1_C4_1] = 0;
			motor[mtr_S1_C4_2] = 0;

			wait10Msec(100);

			StartTask((driveStyle == 0) ? AwesomeDrive : LameDrive);
			StartTask(Arm);
			StartTask(Buttons);
		}

		messageCountPrev = ntotalMessageCount;
		wait10Msec(100);
	}

}
