#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     mux,            sensorI2CCustom)
#pragma config(Sensor, S4,     htspb,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     leftFront,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftRear,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightFront,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     rightRear,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     intake,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    inputstop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    hook1,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    hook2,                tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    irTurret,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    ultraTurret,          tServoStandard)
#pragma config(Servo,  srvo_S1_C4_6,    output,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define ir msensor_S3_1
#define touch msensor_S3_2
#define accel msensor_S3_3
#define ultraSonic msensor_S3_4
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
#include "hitechnic-sensormux.h"
#include "hitechnic-accelerometer.h"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{


	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void Move(float distance, float power)
{
	float offset = 0;
	int xRaw, yRaw, zRaw = 0;

	float xAccel = 0;
	float prevXAccel = 0;

	float deltaTime = 0;

	float velocity = 0;
	float prevVelocity = 0;

	float dist = 0;

	power = abs(power) * sgn(distance);
	if(abs(distance) <= 25)
		distance = abs(distance) - 6;
	else
			distance = abs(distance);
	float accelBias = 0;
	for (int i = 0; i < 20; i++)
	{
		HTACreadAllAxes(accel, xRaw, yRaw, zRaw);
		accelBias += xRaw;
	}
	offset = accelBias/20;
	writeDebugStreamLine("%f", offset);

	float setPower = 0;
	ClearTimer(T1);
	while (true)
	{
		if (abs(dist) < distance)
		{

			setPower = power;
		  if (setPower > power)
		  	setPower = power;
			motor[rightFront] = setPower;
			motor[rightRear] = setPower;
			motor[leftFront] = setPower;
			motor[leftRear] = setPower;

			HTACreadAllAxes(accel, xRaw, yRaw, zRaw);

			xAccel = (((float)xRaw - offset)/ 200.0) * 386.09;

			deltaTime = time1[T1] * 0.001;


			if (abs(xAccel) <= 0.01)
				xAccel = 0;

			velocity += deltaTime/2 * (prevXAccel + xAccel);
			dist += deltaTime/2 * (prevVelocity + velocity);

			ClearTimer(T1);

			prevXAccel = xAccel;
			prevVelocity = velocity;
			wait1Msec(10);

		}
		else
		{
			if(motor[rightFront] != 0)
			{
			motor[rightFront] = 5 * -sgn(setPower);
			motor[rightRear] = 5 * -sgn(setPower);
			motor[leftFront] = 5 * -sgn(setPower);
			motor[leftRear] = 5 * -sgn(setPower);
			wait10Msec(5);
		}
			motor[rightFront] = 0;
			motor[rightRear] = 0;
			motor[leftFront] = 0;
			motor[leftRear] = 0;
		}
	}
}

task main()
{
	initializeRobot();

	//clearDebugStream();
	//waitForStart();   // wait for start of tele-op phase

	Move(-20, 40);
}
