#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     B_R,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     B_L,           tmotorTetrix, PIDControl, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     flag_arm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     block_arm,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     winch,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    hand,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    hook,                 tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This  file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////
float GyroBias = 0;
int avgdata = 0;
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.nclude "Move.c"
#include "move_2_wheel.c"
#include "turn_gyro_2_wheel.c"
//#include "arm2.c"
//#include "Turn_Gyro.c"
//#include "move2.5_452.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////


void initializeRobot()
{
int nDelay = 200;

	bFloatDuringInactiveMotorPWM = false;

	motor(B_L) = 0;
	motor(B_R) = 0;

	 for (int i = 0; i < 20; i++) {
    avgdata += SensorValue[Gyro];
    wait1Msec(25);}
	}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	Turn(360);
	wait10Msec(200);

	Turn(-180);
	wait10Msec(200);

	Turn(180);
	wait10Msec(200);

	Turn(360);
	wait10Msec(200);

	Turn(-180);
	wait10Msec(200);

	Turn(180);
	wait10Msec(200);

	Turn(360);
	wait10Msec(200);

	Turn(-180);
	wait10Msec(200);

	Turn(180);
	wait10Msec(200);

}
