#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorB,          Flag1,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Flag2,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     R_Motor,       tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     L_Motor,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Winch,         tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     Arm,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     Block_Sweep,   tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    Bucket_Release,       tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

float GyroBias = 0;
int avgdata = 0;
task Arm_hold;
#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.nclude "Move.c"
#include "arm2.c"
#include "Turn_Gyro.c"
#include "Move_3_452.c"

bool Hold_enable = false;




/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Take 20 readings of the gyro and average them out
	for (int i = 0; i < 20; i++) {
		avgdata += SensorValue[Gyro];
		wait1Msec(25);
	}
	// Store new bias
	GyroBias = ((float)avgdata / 20);

	int nDelay = 200;

	bFloatDuringInactiveMotorPWM = false;
	motor(R_Motor) = 0;
	motor(L_Motor) = 0;
	nMotorEncoder[R_Motor]	= 0;
	nMotorEncoder[L_Motor]	= 0;

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	StartTask(Arm_hold);
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.
  nMotorEncoder[R_Motor] = 0;
  nMotorEncoder[L_Motor] = 0;

	Move (1,75);
	wait10Msec(55);

	Arm_move(-100);
	wait10Msec(55);

//	Hold_enable = true;

	servo[Bucket_Release] = 255;
	wait10Msec(55);

	servo[Bucket_Release] = 0;
	wait10Msec(55);

	Arm_move(100);
	wait10Msec(55);

	Move(-1, 75);
	wait10Msec(55);

	Turn(40);
	wait10Msec(55);

	Move(30,100);
	wait10Msec(55);

	Turn(-85);
	wait10Msec(55);

	Move(30,100);
	wait10Msec(55);

	/*Turn(-90);
	wait10Msec(55);

	Move(80,100);
	wait10Msec(55);*/

} // End main task

task Arm_hold()
{
	bool Pre_hold = false; // Previous hold state.
	nMotorPIDSpeedCtrl[Arm] = mtrNoReg;
	const int DEAD_BAND = 5; // In degrees
	int direction = 0;
	int power = 30;
	int prevEncodeSmall = 0;
	int prevEncodeLarge = 0;
	int small_diff = 0;
	int large_diff = 0;
	while (true)
	{
	  // Performs the task at 50 Hz.
		if (nPgmTime % 20 == 0)
		{
			// If the hold has just transitioned to hold
		  // initialize all the variables
			if ( (Pre_hold == false) && (Hold_enable == true) )
			{
				nMotorEncoder[Arm] = 0;
				direction = 0;
				small_diff = 0;
				large_diff = 0;
			}

			if (Hold_enable && Pre_hold)
			{
				// Determine if the arm needs to move and the direction
				if (nMotorEncoder[Arm] > DEAD_BAND )
				{
					direction = 1;
					small_diff = nMotorEncoder[Arm] - prevEncodeSmall;
					prevEncodeSmall = nMotorEncoder[Arm];
					if (nPgmTime % 500 == 0)
					{
						large_diff = nMotorEncoder[Arm] - prevEncodeLarge;
						prevEncodeLarge = nMotorEncoder[Arm];
					}
				}
				else if ((nMotorEncoder[Arm] < -DEAD_BAND ))
				{
					direction = -1;
					small_diff = prevEncodeSmall - nMotorEncoder[Arm];
					if (nPgmTime % 500 == 0)
					{
						large_diff = prevEncodeLarge - nMotorEncoder[Arm];
						prevEncodeLarge = nMotorEncoder[Arm];
					}
				}
				else
					direction = 0;

				// Need to move the arm
				if (direction != 0)
				{
					// If the arm is moving further away from zero
				  // at a fast rate, then increase the power fast.
					if (small_diff > 2)
					{
						power = power + (small_diff * 5);
					}

					// If the direction changed, then zero position
					// was over shot.
					else if (small_diff < -2)
					{
						power = power - small_diff;
					}

					// If the arm is moving further away from zero
				  // at a slow rate, then increase the power slowly.
					else if (large_diff > 0)
					{
						power = (large_diff > 10) ? power + 10 : power + large_diff;
					}

					// If the direction changed, then zero position
					// was over shot.
					else if (large_diff < 0)
					{
						power = (large_diff < -10) ? power - 10 : power - large_diff;
					}

					// Move the arm
					motor[Arm] = direction * power;
				}


			} // End if hold is enabled

			Pre_hold = Hold_enable;

   } // End of 50 Hz check
	} // End while true
} // End of task Arm_hold()
