#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     IR,             sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     SONAR_1,        sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     belt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     rightDrive,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    srelease,             tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
float GyroBias = 0;
int avgdata = 0;
#include "Turn_Gyro.c"
#include "move_3_452.c"
#include "arm_linear.c"

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Take 20 readings of the gyro and average them out
	for (int i = 0; i < 20; i++) {
		avgdata += SensorValue[Gyro];
		wait1Msec(25);
	}
	// Store new bias
	GyroBias = ((float)avgdata / 20);

	int nDelay = 200;

	bFloatDuringInactiveMotorPWM = false;
	motor(rightDrive) = 0;
	motor(leftDrive) = 0;
	nMotorEncoder[rightDrive]	= 0;
	nMotorEncoder[leftDrive]	= 0;

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart(); // Wait for the beginning of autonomous phase.
//servo[stilt] = 35;
float COUNTS_PER_INCH = 18.482;
int DistFrom = 14;
int Deadband = 1;
int step = 0;
int cnt = 0;
bool foundGoal = false;

while( foundGoal == false )
{
	switch( step )
	{
		// Initial move
		case 0:
			/*if( ( nMotorEncoder[ leftDrive] / COUNTS_PER_INCH) > 80 || ((nMotorEncoder[rightDrive] / COUNTS_PER_INCH) > 80 ) )
			{
				step = 1;
			}
			if ((SensorValue[SONAR_1] < DistFrom - Deadband))
				{
					motor[leftDrive] = 30;
					motor[rightDrive] = 7;
		  	 }
		  else if ((SensorValue[SONAR_1] > DistFrom + Deadband))
		  	{
		  		motor[leftDrive] = 7;
		  		motor[rightDrive] = 30;
		  	}*/
		  	Move(-50,75);
		  	wait10Msec(55);
		  	step = 1;
			break;

		// Are we in front of the goal
		case 1:
		  // If it is 6, then it is in front of the goal
			if (SensorValue[IR] == 5)
			{
				step = 4;
			}
			// Go to step 2
			else if( cnt < 1 )
				step = 2;
		else if( cnt < 2 )
				step = 3;
		  else
		  	step = 4;
		 cnt++;

			break;

		// rotate and move to next position
		case 2:
			Turn(-45);
			wait10Msec(55);

			Move(-25,75);
			wait10Msec(55);

			step = 1;
			break;

			case 3:
			Turn(-45);
			wait10Msec(55);

			Move(-25,75);
			wait10Msec(55);

			step = 1;
			break;


		// In front of IR, now rotate and move to the goal
		case 4:
			Turn(-90);
			wait10Msec(55);

			Move(-18,75);
			wait10Msec(55);

			Move(5,100);
			wait10Msec(55);

			Turn(-45);
			wait10Msec(55);

			Move(-3,75);
			wait10Msec(55);

			Turn(45);
			wait10Msec(55);

			Move(-5,100);
			wait10Msec(55);



			foundGoal = true;
			break;

		default:
			break;

	} // End of Switch( step )

} // End While true
}
